### ISSUE TITLE
加载预训练权重

### ISSUE THREAD

**Issue by lizifan123** [hukaixuan19970627/OrientedRepPoints#12]
您好，请问再加载预训练权重使，一直报OSError: /weights/swin_large_patch4_window7_224_22k.pth is not a checkpoint file.  该怎么解决呢？万分感谢。

**Comment by 2324773711** [comment]
请问预训练权重您使用那个版本的torch加载的，我这边一直报错版本太低，我是用1.4版本的命令checkpoint = torch.load(filename, map_location=‘cpu’)
