### ISSUE TITLE
No such file or directory: 'work_dirs/r50_dotav1/results.pkl'

### ISSUE THREAD

**Issue by zhanguser0614** [hukaixuan19970627/OrientedRepPoints#8]
作者大大，我测试时显示并没有.pkl文件，然而train之后的work_dirs文件夹里面也并未有该类型的文件，还请大佬指明

**Comment by hukaixuan19970627** [comment]
你先按照getstart.md先运行一遍demo

**Comment by zhanguser0614** [comment]
是这样的作者大大，刚刚我按照你的getstard.md运行了几遍，其中train是没问题的，但是测试的时候，demo里有这么一句--out 'work_dirs/r50_dotav1/results.pkl'，按我的理解就是需要把结果输入的这么一个.pkl文件里，但是运行测试的时候显示并没有work_dirs/r50_dotav1/results.pkl文件存在，我看了一下test的源码，里面--out默认的路径是tools/parse_pkl/demo.pkl，然而我经过训练之后也没有这么一个.pkl文件出现在tools/parse_pkl文件夹下面。刚刚入门新手，还望作者解惑。我的理解是经过train之后的工作文件夹应该会出现一个.pkl文件，可是并没有出现

**Comment by zhanguser0614** [comment]
今早已解决问题，感谢作者
