### ISSUE TITLE
可视化的结果

### ISSUE THREAD

**Issue by zhanguser0614** [hukaixuan19970627/OrientedRepPoints#9]
作者大大我是在服务器跑的这个项目，我这个可视化的结果无法显示，这个有输出可视化结果的模块吗，就是把可视化的结果图片输出到一个文件夹下面

**Comment by hukaixuan19970627** [comment]
ReadMe里有
![image](https://user-images.githubusercontent.com/72599120/167342949-2ffdf8d3-c6eb-493b-b83f-722440a94a03.png)

**Comment by zhanguser0614** [comment]
我刚刚运行了这个文件，结果就是产生一个vis_result文件夹，但是文件夹下面并没有图片

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/167355368-18c101e7-c87f-4572-b911-95e8d10a19b4.png)
1. 除了outpath各个输入都要相互对应
2. 如果没有改动过任何demo，成功运行完getstart.md之后直接在命令行输入以下命令就行
```python
python tools/parse_results_pkl/show_learning_points_and_boxes.py
```

**Comment by zhanguser0614** [comment]
谢谢你，我想问一下预训练模型swin_tiny_patch4_window7_224_torch2.pth是自己训练的吗，还是下载的，如果是下载的去哪儿下呢

**Comment by hukaixuan19970627** [comment]
> 谢谢你，我想问一下预训练模型swin_tiny_patch4_window7_224_torch2.pth是自己训练的吗，还是下载的，如果是下载的去哪儿下呢

![image](https://user-images.githubusercontent.com/72599120/167850024-a395d149-7816-4384-addd-4868ca8ba262.png)

**Comment by zhanguser0614** [comment]
太感谢了，我想问下这个大概训练多次个epoch合适呀，我训练两百次，最后测试的结果才map50左右，太糟心了，训练了好久呢

**Comment by hukaixuan19970627** [comment]
> 太感谢了，我想问下这个大概训练多次个epoch合适呀，我训练两百次，最后测试的结果才map50左右，太糟心了，训练了好久呢

36个epoch
